### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by woutersf** [GrapesJS/preset-newsletter#103]
I am working on a Block that fetches remote content from a JSON feed (this is interesting for pre-filling newsletters). 

<img width="1309" alt="Screenshot 2021-05-12 at 14 59 08" src="https://user-images.githubusercontent.com/592312/117979332-127fc700-b333-11eb-9e6b-49fadaa84995.png">

I am doing this here in this github repo:
https://github.com/woutersf/grapesjs-block-drupal-content-feed

It is not clear for me how I should make this (custom) block configurable. 
If users want for example to render the content in different html (in columns for example).
Is there a possibility to ad an overlay of sorts with configuration or should I configure this externally and add it to the plugin options?

**Comment by artf** [comment]
This could be achieved by creating a custom [component](https://grapesjs.com/docs/modules/Components.html)
