### ISSUE TITLE
Block placeholder is using http

### ISSUE THREAD

**Issue by ghimes** [GrapesJS/preset-newsletter#108]
Hello,
The placeholder for the images in some blocks are using http. When using https for your website, you will get this error in the console:

> Mixed Content: The page at 'about:blank' was loaded over HTTPS, but requested an insecure element 'http://placehold.it/250x150/78c5d6/fff/'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
> placehold.it/250x150/78c5d6/fff/:1 GET https://placehold.it/250x150/78c5d6/fff/ net::ERR_CERT_DATE_INVALID

Here is code from the repo.
https://github.com/artf/grapesjs-preset-newsletter/blob/6308db80c9fdfa91af1dae8bf3f97d1066dde67f/src/blocks.js#L145

Please help me solve this.

**Comment by artf** [comment]
Closing as already fixed
