### ISSUE TITLE
Clicking enter does not expand the text window

### ISSUE THREAD

**Issue by MortenSpjotvoll** [GrapesJS/preset-newsletter#114]
Steps to reproduce:
1. Go to https://grapesjs.com/demo-newsletter-editor.html
2. Insert a Text component
![image](https://user-images.githubusercontent.com/70020680/158985709-861e2c3b-ff49-4b97-8137-0623ad6609af.png)
3. Enter the text component and click enter
![image](https://user-images.githubusercontent.com/70020680/158985752-1af1dd2f-8884-4192-8cee-f0b96f36722a.png)
4. Enter any other character, including backspace, and it will update correctly
![image](https://user-images.githubusercontent.com/70020680/158985947-f5572f4a-51eb-4b2a-83a0-7510240efcaa.png)

Considering enter has some special functionality (insert p or br tags) I guess it uses a preventDefault that stops the height style from updating. As can be seen in the screenshots the height of the gjs-tools stays the same no matter how many times you press enter, but changes correctly once you use another key. If that's the case then this could be a really quick fix for you who are familiar with the code @artf 

There's also an issue the first time you click into a text element, the toolbar spawns directly in front of the text instead of above/below.

**Comment by artf** [comment]
This should be fixed with the latest release of the ckeditor plugin
