### ISSUE TITLE
Is this compatible with latest grapesjs version?

### ISSUE THREAD

**Issue by Abhi0725** [GrapesJS/preset-newsletter#117]
I just updated grapesjs version to the latest one and started having issues with this plugin. Is this updated? I see the last release is from 2018.

**Comment by pratheeke** [comment]
> 

Same here. Were you able to resolve the issue ?

**Comment by svestu** [comment]
+1

**Comment by artf** [comment]
New refactored version of the plugin is [released](https://github.com/GrapesJS/preset-newsletter/releases/tag/v1.0.1)
