### ISSUE TITLE
Remove Category Label Plugin Option

### ISSUE THREAD

**Issue by giltee** [GrapesJS/preset-newsletter#126]
The update last night removed the category label option from plugin options on the default blocks.

[blocks.ts](https://github.com/GrapesJS/preset-newsletter/blob/master/src/blocks.ts)
[Remove categoryLabel option](https://github.com/GrapesJS/preset-newsletter/commit/b27b959692103a959e6e31493ddca01cf2221a31)
yesterday

Now the blocks are just hanging in no category, which is not ideal.

![image](https://user-images.githubusercontent.com/26775901/216401358-16a3472d-8681-4e20-919f-da3ae46aa200.png)

What are we supposed to use instead of the category label now?

**Comment by artf** [comment]
There is a new [`block` option available](https://github.com/GrapesJS/preset-newsletter#options) to handle custom block properties like category
