### ISSUE TITLE
Disable some blocks

### ISSUE THREAD

**Issue by SwithFr** [GrapesJS/preset-newsletter#25]
Is it possible in the options to disable or replace some blocks ?

thks

**Comment by artf** [comment]
Unfortunately not yet in this plugin 😬

**Comment by Keyyubi** [comment]
I guess you do something like this to exclude some blocks from your editor instance.

`excludedModules: [
        "sect100",
        "sect50",
        "sect30",
        "sect37",
        "button",
        "divider",
        "text",
        "text-sect",
        "image",
        "quote",
        "grid-items",
        "list-items",
        "link-block",
        "link"
      ],`

`this.excludedModules.forEach(x =>
        this.grapesEditor.BlockManager.remove(x)
      );`
