### ISSUE TITLE
Uneditable text with Link

### ISSUE THREAD

**Issue by ghost** [GrapesJS/preset-newsletter#33]
This piece of HTML code (taken live from example email template) is not editable via wysiwyg editor, except for the link text.

This is caused by inserting a link into a text most likely.

```html
<div class="c2421" style="box-sizing: border-box; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;">
  MADE BY 
  <a class="link" href="https://github.com/artf" style="box-sizing: border-box; color: rgb(217, 131, 166);">ARTUR
    ARSENIEV</a>
  <p style="box-sizing: border-box;">
  </p>
</div>
```

**Comment by shareefhiasat** [comment]
@rafal-olszewski  can you provide more info , or have jsfiddle you can fork this fiddle
https://jsfiddle.net/shareefhiasat/4q3kxthj/1/
