### ISSUE TITLE
Do not remove HTML comment

### ISSUE THREAD

**Issue by SwithFr** [GrapesJS/preset-newsletter#37]
Whene you put some content to edit with grapesjs, the editor remove all HTML comment like 
`<!--[if !mso]><!-- -->` so it's impossible to create good responsive template.

 Can you fix that behavior ?

**Comment by IceCrystal0k** [comment]
Use the grapesjs-preset-mjml for responsive templates. It's quite good for that.

Yet i still need the comments for a template engine, to hide the conditions and loops.

**Comment by jereddanielson** [comment]
@IceCrystal0k when you say "include it in the grapejs" do you mean as a plugin? Could you give an example? I too am running into this issue. Thanks!

**Comment by jereddanielson** [comment]
I see, you simply run that function with the editor instance as the argument and it will add the HTML comment node type to the dom components? Thanks!

**Comment by IceCrystal0k** [comment]
You can either create a component with the code above and add it in the plugin list when you initialize grapes. You gonna need node js to compile the component.

Or you could use it directly in your code, after initializing the editor, passing the editor as an argument. In this case just give a name to the function, instead of exporting it.

**Comment by rafal-olszewski** [comment]
@artf could you advice in here ?

This is mandatory behaviour to keep HTML comments within email HTML body. Otherwise, outlook will not show our template properly.

**Comment by artf** [comment]
> This is mandatory behaviour to keep HTML comments within email HTML body. Otherwise, outlook will not show our template properly.

Yes, the comment node is not included by default.

> your solution works when getting HTML body, but when email is being edited in Grapes - it shows up without comments.

I don't get it

**Comment by alxcas1** [comment]
Hello and thank you for this really nice editor which is Grapejs. 

I'm using it with grapejs newsletter and have the same issue as @SwithFr and the conditional comment tag in the editor. 

We try to implement the component mentioned above and it works well but in the edition mode, all the comments are displayed. 

I didn't found if a commit is plan to let grapejs editor read the conditional comment tag or if someone can help on fixing that displaying comment bug. 

Thank you all !

**Comment by artf** [comment]
Closing as the comment component was introduced in the core long time ago
