### ISSUE TITLE
Plase upload a copy of grape.min.js whithout minified

### ISSUE THREAD

**Issue by graphixx** [GrapesJS/preset-newsletter#43]
Plase upload a copy of grape.min.js whithout minified the human sintax spell grape.js for version grapesjs - 0.10.7, best regards

**Comment by IceCrystal0k** [comment]
you can build it yourself;
Just download the code from github for whatever version you need and install nodejs if you don't already have it.
Then open a console window (if you're on windows), go to [grapesjs-preset-newsletter] folder
and type: npm run build-dev
then take the built version from [dist] folder and use it with your grapes.

**Comment by graphixx** [comment]
Thanks bro, in a last years i have a little use of github, in the present i set a thanks for you, REALLY THANKS, best regards.
