### ISSUE TITLE
Unable to add a link on a button

### ISSUE THREAD

**Issue by olasfar** [GrapesJS/preset-newsletter#46]
Hey guys,

I'm getting some errors when I try to add a link on a button. The error is reproducible on the demo https://grapesjs.com/demo-newsletter-editor.html
<img width="1417" alt="capture d ecran 2018-07-17 a 21 08 58" src="https://user-images.githubusercontent.com/1301822/42846135-5bed4b8e-8a18-11e8-819d-0963ad1fd0ac.png">

Please advice,

Thx

**Comment by olasfar** [comment]
cc @artf :)

**Comment by artf** [comment]
It's about configuring CKEditor to accept editing `<a>` elements. PR is welcome
