### ISSUE TITLE
Doubts regarding React integration

### ISSUE THREAD

**Issue by iamjamielobo** [GrapesJS/preset-newsletter#49]
Hi Guys

I've been trying to integrate Grapes in my current React Project.
I'm finding it a bit tedious to get an onChange event to get any of the changes made within the editor.
I'm using the newsletter preset.

My current config looks something like this

`editor = grapesjs.init({
            height: '100%',
            assetManager: {
                assets: images,
                upload: 0,
                uploadText: 'Uploading is not available in this demo'
            },
            container: '#gjs',
            fromElement: true,
            plugins: ['gjs-preset-newsletter']
        })`

Thanks.

**Comment by luishdez** [comment]
I used

`editor.on('component:update', onUpdate);`  and then  

```
  handleUpdateGrape = () => {
    this.setState({
      /* eslint-disable-next-line */
      html: this.editor.runCommand('gjs-get-inlined-html'),
    });
  };
```

**Comment by ramakrishnachowdary** [comment]
Thanks this is working.
