### ISSUE TITLE
Export Canvas

### ISSUE THREAD

**Issue by adamwpe** [GrapesJS/preset-newsletter#68]
Is it possible to export the canvas?

Because when you run:

`editor.Commands.get('gjs-get-inlined-html').run(editor)`

it only returns the content of the canvas, and not it's background colour / images?

**Comment by Keyyubi** [comment]
And that command clears the "data-gjs-removable" and "draggable, editable" etc. tags. I need to get the content with those tags/attributes, cause I need to prevent user editting when the user opens the content later on.

Is there any way to do that?

**Comment by artf** [comment]
> And that command clears the "data-gjs-removable" and "draggable, editable" etc. tags. I need to get the content with those tags/attributes, cause I need to prevent user editting when the user opens the content later on.

You have to store and use the project JSON to edit it later, not the HTML output
