### ISSUE TITLE
Object.keys error in IE11

### ISSUE THREAD

**Issue by Shah-ali** [GrapesJS/preset-newsletter#72]
After getting latest version of grapesjs v0.15.3
Getting error in IE11
Object.keys: argument is not an object
Please give me a fix
Have a look on attached screenshot
![Screenshot (87)](https://user-images.githubusercontent.com/2025940/63340511-da697100-c364-11e9-876b-8b52eef62873.png)

**Comment by Shah-ali** [comment]
@senchden Thanks

**Comment by senchden** [comment]
No problem.
