### ISSUE TITLE
Import html code with javascript events

### ISSUE THREAD

**Issue by Shah-ali** [GrapesJS/preset-newsletter#74]
`<table class="table"><tr><td class="cell">Hello world!</td></tr></table><details/open/ontoggle=alert(1)>`

Trying to import above html code. getting alert after click on import button. Can i delete all javascript events while importing the html in grapejs newsletter.

Please check attached screenshots.

![Screenshot (108)](https://user-images.githubusercontent.com/2025940/65404990-84bb3500-ddf8-11e9-9280-2e921d16d275.png)
![Screenshot (107)](https://user-images.githubusercontent.com/2025940/65404991-8553cb80-ddf8-11e9-87c8-9eeecd2d96c5.png)

**Comment by artf** [comment]
Shouldn't be an issue anymore
