### ISSUE TITLE
Installer checks for Python 2.7

### ISSUE THREAD

**Issue by eyeamkd** [GrapesJS/preset-newsletter#81]
![grapes-error](https://user-images.githubusercontent.com/31094327/74035154-bca9ca00-49df-11ea-95cf-114a9abeaf9e.png)

This is the error that's showing up

_Originally posted by @eyeamkd in https://github.com/artf/grapesjs-preset-newsletter/issues/80#issuecomment-583399511_

**Comment by electric-skeptic** [comment]
Did you find a solution to this?

**Comment by artf** [comment]
looks related to node-saas which is not used in this plugin anymore
